version: 2.1

executors:
  executor:
    working_directory: ~/sched
    docker:
    - image: collegevine/rails-build

jobs:
  build-sched:
    executor: executor
    parallelism: 1
    steps:
    - checkout: { path: "~/sched" }

    - restore_cache:
        keys:
          - mice-schedule-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "packages.dhall" }}-{{ checksum "spago.dhall" }}
          - mice-schedule-v2-{{ .Branch }}-

    - run: cd ~/sched && npm install && sysconfcpus -n 2 npm run build

    - save_cache:
        key: mice-schedule-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "packages.dhall" }}-{{ checksum "spago.dhall" }}
        paths:
          - .spago
          - .cache
          - node_modules
          - output

    - persist_to_workspace:
        root: ~/sched/dist
        paths: [.]

  deploy-sched:
    steps:
      - attach_workspace: { at: ~/dist }

      - run: |
          cd ~/dist
          git init && git add .
          git config user.email "fsoikin@fsoikin.dev"
          git config user.name "CI Deployment"
          git commit -m "CI Deployment"
          git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2.1

  build-and-deploy:
    jobs:
      - build-sched
      - deploy-sched:
          requires: ["build-sched"]
          filters: {branches: {only: "master"}}

