version: 2.1

jobs:
  build:
    working_directory: ~/sched

    docker:
    - image: collegevine/rails-build

    parallelism: 1

    steps:
    - checkout: { path: "~/sched" }

    - restore_cache:
        keys:
          - mice-schedule-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "packages.dhall" }}-{{ checksum "spago.dhall" }}
          - mice-schedule-v1-{{ .Branch }}-

    - run: cd ~/sched && npm install && sysconfcpus -n 2 npm run build

    - save_cache:
        key: mice-schedule-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "packages.dhall" }}-{{ checksum "spago.dhall" }}
        paths:
          - .spago
          - node_modules
          - output