name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          .spago
          output
          node_modules
        key: build-atrifacts-v2-${{ hashFiles('package-lock.json', 'spago.dhall', 'packages.dhall') }}
    - uses: actions/setup-node@v1
      with:
        node-version: 16.15
    - run: npm i
    - run: npm run build
    - name: Deploy
      run: |
        cd ./dist
        echo "{ \"root\": \".\" }" > static.json
        git init && git add .
        git config user.email "fsoikin@fsoikin.dev"
        git config user.name "CI Deployment"
        git commit -m "CI Deployment"
        git push --force https://heroku:${{ Secrets.HEROKU_API_KEY }}@git.heroku.com/${{ Secrets.HEROKU_APP_NAME }}.git master

